// <auto-generated />
using System;
using MageBackend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MageBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604221947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MageBackend.Database.Audit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action_type");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("base_url");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("class");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DiffValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diff_value");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<string>("ExecuteType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("execute_type");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("function");

                    b.Property<string>("Host")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host");

                    b.Property<string>("Hostname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hostname");

                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_user");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("method");

                    b.Property<string>("OriginalUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("original_url");

                    b.Property<string>("Params")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("params");

                    b.Property<string>("Raw")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("table_name");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdUser", "CreatedAt" }, "IX_tb_audit_IdUser_CreatedAt");

                    b.ToTable("tb_audit", "audit");
                });

            modelBuilder.Entity("MageBackend.Database.Auth", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("FirstAccess")
                        .HasColumnType("bit")
                        .HasColumnName("first_access");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<DateTime?>("RequestPasswordExpiration")
                        .HasColumnType("datetime2")
                        .HasColumnName("request_password_expiration");

                    b.Property<string>("RequestPasswordToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_password_token");

                    b.Property<int>("Retries")
                        .HasColumnType("int")
                        .HasColumnName("retries");

                    b.Property<int>("SessionVersion")
                        .HasColumnType("int")
                        .HasColumnName("session_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Auth", (string)null);
                });

            modelBuilder.Entity("MageBackend.Database.ErrorLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_data");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_user");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("tb_error_log", "audit");
                });

            modelBuilder.Entity("MageBackend.Database.Feature", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Feature", (string)null);
                });

            modelBuilder.Entity("MageBackend.Database.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("sku");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IdUser");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("MageBackend.Database.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("MageBackend.Database.RoleFeature", b =>
                {
                    b.Property<string>("IdRole")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_role");

                    b.Property<string>("IdFeature")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_feature");

                    b.Property<bool>("Activate")
                        .HasColumnType("bit")
                        .HasColumnName("activate");

                    b.Property<bool>("Create")
                        .HasColumnType("bit")
                        .HasColumnName("create");

                    b.Property<bool>("Delete")
                        .HasColumnType("bit")
                        .HasColumnName("delete");

                    b.Property<bool>("View")
                        .HasColumnType("bit")
                        .HasColumnName("view");

                    b.HasKey("IdRole", "IdFeature");

                    b.HasIndex("IdFeature");

                    b.ToTable("RoleFeature", (string)null);
                });

            modelBuilder.Entity("MageBackend.Database.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar");

                    b.Property<string>("CognitoId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("cognito_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("IdAuth")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_auth");

                    b.Property<string>("IdRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_role");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CognitoId");

                    b.HasIndex("Document");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdAuth");

                    b.HasIndex("IdRole");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MageBackend.Database.Product", b =>
                {
                    b.HasOne("MageBackend.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MageBackend.Database.RoleFeature", b =>
                {
                    b.HasOne("MageBackend.Database.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("IdFeature")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MageBackend.Database.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MageBackend.Database.User", b =>
                {
                    b.HasOne("MageBackend.Database.Auth", "Auth")
                        .WithMany()
                        .HasForeignKey("IdAuth");

                    b.HasOne("MageBackend.Database.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auth");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
